global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'dgmstt-monitor'
    environment: '${ENVIRONMENT:-dev}'

scrape_configs:
  # DGM Agent Orchestrator metrics
  - job_name: 'orchestrator'
    static_configs:
      - targets: ['orchestrator:9091']
        labels:
          service: 'agent-orchestrator'

  # Individual Agent metrics
  - job_name: 'agents'
    dns_sd_configs:
      - names:
          - 'agent-*.dgmstt-network'
        type: 'A'
        port: 9092
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}'

  # RabbitMQ metrics
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
        labels:
          service: 'rabbitmq'

  # Redis metrics (via redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'

  # Node exporter for host metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node-exporter'

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

# Alerting rules
rule_files:
  - '/etc/prometheus/alerts/*.yml'

# AlertManager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'